### ISSUE TITLE
Missing artifact 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by nikhil2108** [rishabh9/riko#3]
3.0.0-SNAPSHOT is not present in maven central repository. Please upload it.

**Comment by rishabh9** [comment]
It is available under the [SNAPSHOT repository](https://oss.sonatype.org/content/repositories/snapshots/com/github/rishabh9/riko/3.0.0-SNAPSHOT/). Enable the snapshot repository in your project to download the dependency.
