### ISSUE TITLE
Incorrect Historical API url for 3.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by nikhil2108** [rishabh9/riko#4]
Getting error when called historical apis
`{
    "message": "'3861c062b31ce5548248ba062136b19a1499af52' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer 3861c062b31ce5548248ba062136b19a1499af52'."
}`

I found that this is because of library is using incorrect url for getOHLC().

> https://staging-api.upstox.com/historical/ohlc/NSE_EQ/HEG/1?start_date=02-01-2018&end_date=09-01-2018&format=json

"/ohlc" is not present in new url. 

> https://staging-api.upstox.com/historical/NSE_EQ/HEG/1?start_date=02-01-2018&end_date=09-01-2018&format=json

Removing /ohlc should work.

**Comment by rishabh9** [comment]
Thanks for pointing this out! Fixed the URL. Please check.
