### ISSUE TITLE
Upstox has stopped their data APIs for new users.

### ISSUE THREAD

**Issue by nikhil2108** [rishabh9/riko#7]
I had used this library for sometime, but recently when I checked, Upstox is allowing data api access only to closed set of users. Unfortunately I unsubscribed from their data apis few months back and now they are not letting me to subscribe again.
Any alternate solution or workaround for getting NSE data. I don't need realtime data. Closing basis would work.
I checked other vendors like Globaldatafeeds etc. but they are charging hell lot of money.

**Comment by rishabh9** [comment]
I would still recommend GDF at this moment. Or move onto another broker.
Else you'll have to scrape NSE.

**Comment by nikhil2108** [comment]
Yes. Scraping data for now. Tedious but free. Thanks for the inputs.
